[supervisord]
nodaemon=true
user=root

# Service 1: Flowork Core (Jalan dari folder hasil git clone)
[program:flowork-core]
directory=/app/code/flowork-core
command=python3 run_server.py
autostart=true
autorestart=true
stdout_logfile=/var/log/core.out.log
stderr_logfile=/var/log/core.err.log

# Service 2: Gateway
[program:flowork-gateway]
directory=/app/code/flowork-gateway
command=python3 run_gateway.py
autostart=true
autorestart=true
stdout_logfile=/var/log/gateway.out.log
stderr_logfile=/var/log/gateway.err.log

# Service 3: GUI Server (Nginx)
[program:nginx-gui]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true